### ISSUE TITLE
test_krylov unit tests are inconsistent

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#144]
I noticed that running the unittests on test_krylov fail every now and then and I think it's due to the random vectors and the assumptions on the results.  E.g. 

    for n in {1..100}; do nosetests-2.7 test_krylov.py -v; done

will fail at a couple of locations (for me):
line 99: comparing CR and GMRES residual vectors
and
line 168: testing bicgstab convergence

I believe bicgstab is failing because the requirements on the residual are too tight (and the A-norm of the error is only guaranteed...).

I'm not sure about the CR test...

**Comment by lukeolson** [comment]
I can no longer reproduce this.  So I'm closing this @c7b54be0b3df46f9736a973dbadca226a0a38f06.  If we can narrow the issue to a certain numpy/scipy combination, then let's reissue.

**Comment by jbschroder** [comment]
sounds good to me.
