### ISSUE TITLE
Default GMRES Inconsistent Between Code/Documentation

### ISSUE THREAD

**Issue by eecarrier** [pyamg/pyamg#157]
Documentation for GMRES says that it defaults to Householder implementation.  But looking at source code for GMRES, it appears as if it is defaulting to Modified Gram-Schmidt.

**Comment by lukeolson** [comment]
For some reason it was changed in d89d656fc19ccc2e2ad454d2dca22016c0ae24d6

@jbschroder Any ideas why?  

I added it back.

**Comment by lukeolson** [comment]
It appears the default of householder crashes some tests.  I'll start looking into it.

**Comment by lukeolson** [comment]
@eecarrier this is fixed now in f14592927ef462563b675ebd5aba5d51956e9370

householder is the default and the tests pass.  Le me know if you encounter problems.
