### ISSUE TITLE
MGS and Householder

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#158]
======================================================================
FAIL: test_gmres (test_krylov.TestKrylov)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyamg/krylov/tests/test_krylov.py", line 117, in test_gmres
    results for small matrix')
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals
Householder GMRES and MGS                                                   GMRES gave different                                                   results for small matrix
(mismatch 75.0%)
 x: array([-0.917289, -0.379781,  0.      ,  0.119777])
 y: array([ 0.237538,  0.926397,  0.      , -0.292171])

**Comment by lukeolson** [comment]
This was closed previously...but it has reemerged:

https://github.com/pyamg/pyamg/issues/144

**Comment by lukeolson** [comment]
@jbschroder any ideas on this?  I think we should take care of the KnownFailures in the tests...  I took a look at this again in the 3.0 upgrade #152 but didn't see where it was coming from

**Comment by jbschroder** [comment]
If you do a

git diff dff20ce94ce8b0d4d4b1eb79143e54bf5d929e2a
fd6b89edb809e3a934d53a5db18b45fc50fd943a krylov.h

Then you'll see that a typo regarding "2" versus "-2" got introduced into
the Horner scheme.  I think its fixed now.  I had to do a
"rm -rf build" to get stuff to work.

- Jacob

**Comment by lukeolson** [comment]
Great find.  I believe I was tracking down some casting issues with SWIG when writing it as `*(-2.0)` and ended up losing the `-`.

I'm curious as to why these were `KnownFailure`s before as it doesn't appear that this was ever addressed. Anyway it passes now.

**Comment by lukeolson** [comment]
I think one issue was the way complex values were handled.  In the new version of the SWIG wrapper everything uses `std::complex` instead of `complex_ops.h`

This likely helped with f14592927ef462563b675ebd5aba5d51956e9370
