### ISSUE TITLE
Oblique Krylov does not converge correctly

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#159]
======================================================================
FAIL: test_krylov (test_krylov.TestKrylov)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyamg/krylov/tests/test_krylov.py", line 156, in test_krylov
    err_msg='Oblique Krylov Method Failed Test')
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal: Oblique Krylov Method Failed Test
 ACTUAL: False
 DESIRED: True

**Comment by lukeolson** [comment]
previously closed:
https://github.com/pyamg/pyamg/issues/144

**Comment by lukeolson** [comment]
@jbschroder I think this is the 'other' knownfailure

**Comment by jbschroder** [comment]
If you do a

git diff dff20ce94ce8b0d4d4b1eb79143e54bf5d929e2a
fd6b89edb809e3a934d53a5db18b45fc50fd943a krylov.h

Then you'll see that a typo regarding "2" versus "-2" got introduced into
the Horner scheme.  I think its fixed now.  I had to do a
"rm -rf build" to get stuff to work.

- Jacob

**Comment by lukeolson** [comment]
closing for now #158
