### ISSUE TITLE
GMRES doesn't return residuals list

### ISSUE THREAD

**Issue by arsenovicpt** [pyamg/pyamg#160]
Calling gmres with the following syntax gmres(A,b,tol=1e-3,resisuals=[]) does not return the residuals list. Instead, only the solution vector 'x' and 'info' is returned.

**Comment by lukeolson** [comment]
You'll have to create the list before the call:
```
res = []
x, info = gmres(A,b,tol=1e-3,resisuals=res)
```

**Comment by arsenovicpt** [comment]
Thanks!
