### ISSUE TITLE
'Illegal Instruction' error on some CPU types

### ISSUE THREAD

**Issue by mtszyk** [pyamg/pyamg#162]
Attempting to instantiate a smoothed aggregate solver causes python to exit with the 'illegal instruction' error and exit code (132). It does not happen with a rootnode_solver, or ruge_stuben_sovler.

Additionally, after instantiating the solver and setting up a preconditioner, all of the krylov solving methods fail. See the python file for detail.

The example system provided is essentially diffusion with no flux on the bottom and period boundary conditions on the sides, and a source at the top and sinks on the bottom.

An example script with data to load is attached, and a truncated cpuinfo of the machines that failed and had a success are attached. The cpuinfo that was truncated was just repeated info for identical cores on one system.

Note: added .txt to all files to allow uploading.
[amd_success.txt](https://github.com/pyamg/pyamg/files/51250/amd_success.txt)
[amd_fail.txt](https://github.com/pyamg/pyamg/files/51251/amd_fail.txt)
[illegal_instruction.py.txt](https://github.com/pyamg/pyamg/files/51253/illegal_instruction.py.txt)
[testA.mtx.txt](https://github.com/pyamg/pyamg/files/51252/testA.mtx.txt)
[intel_fail.txt](https://github.com/pyamg/pyamg/files/51248/intel_fail.txt)
[testb.mtx.txt](https://github.com/pyamg/pyamg/files/51249/testb.mtx.txt)

**Comment by lukeolson** [comment]
Do you still see issues with the latest version?

**Comment by mtszyk** [comment]
Sorry for the delay, no longer appears under any condition I tested.
