### ISSUE TITLE
relaxation on normal equations and normal residual equations

### ISSUE THREAD

**Issue by ben-s-southworth** [pyamg/pyamg#191]
Few things:

- There is a bug somewhere in get_diagonal(A, norm_eq=2), because in practice this is not equivalent to get_diagonal(A.T*A, norm_eq=1). This causes jacobi_ne, gaussseidel_ne, etc. to not work properly.

- Somehow I see different behavior in the amg_core C function for jacobi_ne vs. a pure python implementation. I believe the iteration in python should be 
    for i in range(0,iterations):
        res = A.T * (b - A*x)
        temp =  x + Dinv * res
where Dinv is Dinv(A^TA), but this returns different stuff than the amg_core version.

- For gaussseidel_ne and jacobi_ne : I assume "ne" stands for normal equations. But, in the descriptions, the normal equations are not used, the normal residual equations are. The normal equations are given by A^TAx = A^Tb, and the normal residual equations are AA^Ty = b, and x = A^Ty. What is actually happening in the code? Need to make sure descriptions and function names are accurate.

**Comment by lukeolson** [comment]
@ben-s-southworth Can you provide a test that succeeds/fails?  Is this still an issue?
