### ISSUE TITLE
Convergence History

### ISSUE THREAD

**Issue by cortner** [pyamg/pyamg#194]
Is there a way to extract the convergence history from, say, the blackbox solver? I tried using `return_solver`, but couldn't find where (if?) the history information is stored.

**Comment by lukeolson** [comment]
Ok, this should do it: 2227b77522a2d8e6ffb61c89416a81c88854e297

One thing to note is that you'll get the residual in the preconditioned norm (||r||_M where M is the multigrid preconditioner).

```
import pyamg
import numpy as np
A = pyamg.gallery.poisson((100, 100), format='csr')
b=np.ones(A.shape[0])
x0 = np.ones(A.shape[0])
res = [];
x = pyamg.blackbox.solve(A, b, x0=x0, residuals=res)
```

output:
```
  Detected a Hermitian matrix
    maxiter = 400
    iteration 1
    iteration 2
    iteration 3
    iteration 4
    iteration 5
  Residuals ||r_k||_M, ||r_0||_M = 1.13e-02, 1.63e+03
  Residual reduction ||r_k||_M/||r_0||_M = 6.89e-06
```

**Comment by cortner** [comment]
thank you for this - I also see this was previously available if calling with an AMG object, sorry I missed it in the documentation. 

Turns out I am still having some difficulty but it is due to Julia-Python interaction so my problem.

**Comment by lukeolson** [comment]
No worries.  The blackbox `solve` needed some consistency with the ml `solve` so this needed to be done anyway.
