### ISSUE TITLE
Missing wheels for windows

### ISSUE THREAD

**Issue by mariaza** [pyamg/pyamg#195]
It would be great to have wheels for windows 10 available for major python versions (e.g. 3.4).

**Comment by lukeolson** [comment]
I agree - any recommendations on generating them?  I'd be happy to add this to the release.

**Comment by askaribragimov** [comment]
Hello, I beleive one can use the advice from 
https://packaging.python.org/distributing/#wheels 
and http://pythonwheels.com/ ("My Package is White").

Basically it seems to boil down to have a right machine and issue packaging commands

The tricky thing that one has to use different compilers, namevy MS VS 2010 for wheel targeted at pything 3.4 and 2015 for later versions. At least one would suffice I believe. MSVS2010  itself has difficulties installing on Windows 10. 

http://stackoverflow.com/questions/37534000/python-3-4-windows-10-and-unable-to-find-vcvarsall-bat/37631048#37631048

**Comment by lukeolson** [comment]
This may be an option https://mingwpy.github.io/

**Comment by lukeolson** [comment]
or https://packaging.python.org/guides/supporting-windows-using-appveyor/#access-to-the-built-wheels

**Comment by lukeolson** [comment]
I'll close this until we find a better way to generate.

**Comment by isuruf** [comment]
This can be easily done with appveyor for windows wheels (and travis-ci for osx and linux) using https://github.com/matthew-brett/multibuild
