### ISSUE TITLE
Inconsistent residuals

### ISSUE THREAD

**Issue by lahwaacz** [pyamg/pyamg#204]
What exactly is referred to as a "residual" throughout pyamg? For example [here](http://pyamg.readthedocs.io/en/latest/pyamg.html#pyamg.multilevel.multilevel_solver.solve) in the `residuals` list?

I ask because I have a linear system, for which this code:
```python
A, x0, b = load_system()

residuals = []

ml = pyamg.aggregation.smoothed_aggregation_solver(A, coarse_solver="lu")
x = ml.solve(b, x0, tol=1e-8, accel="gmres", residuals=residuals)

print("residuals: ", np.array(residuals))
print("initial residual: ", np.linalg.norm(b - A*x0))
print("final residual:   ", np.linalg.norm(b - A*x))

```
gives this output:
```
residuals:  [  1.90742365e+03   2.46237095e+02   7.37640869e+01   4.24415154e+01
   2.26020896e+01   1.01097677e+01   6.54103003e+00   2.90056919e+00
   1.21443941e+00   2.94870147e-01   9.30577374e-02   3.87827062e-02
   1.21317950e-02   5.13556765e-03   1.23089031e-03   3.07927290e-04
   9.55081888e-05   2.94020487e-05   8.99521969e-06]
initial residual:  169.162191899
final residual:    7.33922070348e-07
```
Note especially, that the first item in the `residuals` array is `1.90742365e+03` vs. my custom `169.162191899`. For the final residue it's `8.99521969e-06` vs. `7.33922070348e-07`. But we have `8.99521969e-06 / 1.90742365e+03 == 4.715900261591074e-09` and `7.33922070348e-07 / 169.162191899 == 4.338570351383219e-09` which is pretty close and both are less than the specified tolerance as expected.

But with a different system, I get the following output:
```
residuals:  [  7.46798679e+03   6.12041588e+02   2.23696785e+02   4.86324879e+01
   2.12922568e+01   1.72794230e+01   1.34075286e+01   7.11332293e+00
   2.42608324e+00   1.14781268e+00   4.44119832e-01   2.42504621e-01
   1.57739497e-01   4.83938585e-02   2.04185224e-02   9.14724819e-03
   3.50229029e-03   1.03405520e-03   3.19180567e-04   1.20335344e-04
   4.69263331e-05]
initial residual:  139.669408523
final residual:    4.0189140226e-06
```
Here the ratio of the pyamg residuals is `4.69263331e-05 / 7.46798679e+03 == 6.28366578832687e-09`, which is less than the specified tolerance. But the ratio of my residuals is `4.0189140226e-06 / 139.669408523 == 2.8774475850509438e-08`, which is __greater than__ the specified tolerance, so the approximation is not good enough.

The systems are 44684 x 44684 with 442680 nonzeros and 178648 x 178648 with 1778160 nonzeros, respectively, which are still pretty small problems. Please let me know what you need to be able to track this down, I might be able to even provide the linear system data.

**Comment by ben-s-southworth** [comment]
Hi Jakub,
Are you using AMG as a preconditioner? In this case, the preconditioned
residual that is used in the Krylov method is computed and saved. In most
cases this should be a good measure of residual reduction. One could also
compute the actual residual each iteration, but this is an additional matvec
that doesn't contribute to the actual solve. Note that I have experienced
situations (mostly in developing nonsymmetric methods) where I end up
with a singular preconditioner for nonsymmetric problems, and the algorithm
stops because residual went from 10^50 to 10^40... Perhaps there is a check
we should add for situations like this? Or check the actual residual before
stopping?
-ben

**Comment by lahwaacz** [comment]
I'm using the `accel="gmres"` parameter as shown in the code above, not the `aspreconditioner()` method of the [multilevel_solver](http://pyamg.readthedocs.io/en/latest/_modules/pyamg/multilevel.html#multilevel_solver.aspreconditioner). Not sure if there is a difference...

**Comment by ben-s-southworth** [comment]
Setting accel in the solve() routine uses amg as a preconditioner for the
chosen acceleration method. That is, you're using aspreconditioner()
internally. If you use accel=None, you should have an exact match between
returned residuals and anything you compute outside.

**Comment by lahwaacz** [comment]
Indeed, that explains the inconsistencies, thanks for your replies. I'll ask some more details in #203...
