### ISSUE TITLE
Support for user-defined callbacks?

### ISSUE THREAD

**Issue by rc** [pyamg/pyamg#208]
Hi,

is it possible to pass a callback function into the solvers? I can see it in the krylov sub-package solvers, but not in the main MG solvers. I can imagine it could be a bit tricky with all the levels/cycle types, but info on the context could be passed to the callback.

This is motivated by me being unable to find how to obtain the actual number of iterations (on the finest level, of the accelerator?). :)

Best regards,
r.

**Comment by ben-s-southworth** [comment]
Robert, are you just looking for the number of AMG iterations performed
when you call solve()? One easy way to do this is to save the residuals:

    res = []
    ml.solve(b, x0, tol, residuals=res)
    num_iter = len(res)-1,

because the residual list includes the initial residual.
-ben

**Comment by rc** [comment]
On 07/21/2017 10:21 PM, Ben Southworth wrote:
> Robert, are you just looking for the number of AMG iterations performed
> when you call solve()? One easy way to do this is to save the residuals:
> 
>      res = []
>      ml.solve(b, x0, tol, residuals=res)
>      num_iter = len(res)-1,
> 
> because the residual list includes the initial residual.
> -ben

Thanks for the tip - this was my backup idea :) - it will do.

Anyway, having a proper callback mechanism would be handy to get convergence 
information on the fly.

r.

**Comment by rc** [comment]
Oh, I have just now noticed, that the `solve()` method of a constructed ML solver has a `callback` argument. I will try that! (And close this question if that works.)

**Comment by rc** [comment]
All is fine, thanks!
