### ISSUE TITLE
PyAMG does not work with SciPy 1.0

### ISSUE THREAD

**Issue by SpaceCowboy850** [pyamg/pyamg#213]
SciPy 1.0 was released Oct252017.  It looks like it has deprecated/removed calc_work.  Not sure if anything else has been removed.

**Comment by lukeolson** [comment]
We fixed some of it here: https://github.com/pyamg/pyamg/pull/209
and here we dropped 2.6 and 3.3 support https://github.com/pyamg/pyamg/issues/210

What version of numpy and are you using?

**Comment by SpaceCowboy850** [comment]
Sorry - should have put all that:

Python: 3.5.2
OS: Windows 10 64bit
numpy: 1.13.3

Was slamming my head against a wall trying to figure out why this suddenly stopped working when it was working for a co-worker just fine.  I just picked the day that they released SciPy 1.0 to install it.  <facepalm>

**Comment by lukeolson** [comment]
Ok, and you're using pyamg from `master` or from pypi?

**Comment by SpaceCowboy850** [comment]
pip install from a conda virtual env 
pip version 9.0.1 on python 3.5
conda 4.3.27

**Comment by lukeolson** [comment]
oh ic.  The conda recipe will not do it.   It doesn't have this fix.

For now, you can install from `master` -- that should work.

I'll work on a rolling a new release and a new conda recipe.

Thanks for the notification!

**Comment by SpaceCowboy850** [comment]
thanks for the prompt response - was not expecting that!

**Comment by lukeolson** [comment]
ok, i pushed v3.3.2 which should handle scipy 1.0 in https://github.com/pyamg/pyamg/commit/683beda9dff76f0c5270b748431977f76686a76a

**Comment by SpaceCowboy850** [comment]
Looks to be working now - thanks!

**Comment by lukeolson** [comment]
Great.  the conda feedstock has been updated too.

https://github.com/conda-forge/pyamg-feedstock
