### ISSUE TITLE
Multicore support?

### ISSUE THREAD

**Issue by ma-sadeghi** [pyamg/pyamg#221]
I'm not sure if this is the right place to ask questions, sorry for that in advance. Does `pyamg` support multicore CPUs?

**Comment by jbschroder** [comment]
Hi Amin,

This is definitely the right place to ask this question.  Unfortunately,
PyAMG does not support multicore CPUs.  This has been planned, and we've
even done some work towards this.  But there's nothing at the moment.

Sorry!

Jacob

**Comment by ma-sadeghi** [comment]
Hi Jacob,

Thank you for your quick reply! No worries, I look forward to it. And thanks for the lovely/easy-to-use package!

Cheers,
Amin

**Comment by lukeolson** [comment]
I made some progress with just the SpMV:
https://github.com/lukeolson/sparse-ops

In particular, we'll have to adopt some key `scipy.sparse` kernels like this:
https://github.com/lukeolson/sparse-ops/blob/master/sparse.h#L29

SpMV, block SpMV for both CSR and BSR are the first steps, along with SpMM.

Another issue is the setup -- you cannot mix g++ and clang++ compiled c++.  I think it's easy enough to see if hte compiler supports `-fopenmp` and to go from there...

see #227 for updates...
