### ISSUE TITLE
Root-node on block-sparse with non-square blocks?

### ISSUE THREAD

**Issue by jwittke** [pyamg/pyamg#222]
Hi,

I am trying to solve a block sparse linear system which has non-square blocks. 
For this, I setup an sparse matrix like 

`sp_bsr = bsr_matrix((self.val, (self.idx, self.jdx)), dtype=complex, blocksize=(4,1))`

Then, I set up the root-node solver with

`ml = pyamg.rootnode_solver(A, symmetry='nonsymmetric', aggregate='standard', strength=('evolution' {'block_flag': True}), improve_candidates='sor')`

When the code wants to setup the solver I get an error like:

>  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/pyamg/relaxation/smoothing.py", line 568, in smoother
    sweep=sweep)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/pyamg/relaxation/relaxation.py", line 164, in sor
    gauss_seidel(A, x, b, iterations=1, sweep=sweep)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/pyamg/relaxation/relaxation.py", line 332, in gauss_seidel
    raise ValueError('BSR blocks must be square')
ValueError: BSR blocks must be square

From my understanding, and what I saw in the PyAMG code, is that it will use the `improve_candidates` options for the relaxation. And also, if only one argument is stated, it will be used for all levels.
So, why is there a Gauss-Seidel relaxation still present?

In addition, my linear system comes from a pde system where four physical variables are assigned to one degree of freedom. So, every block should represent a geometrical point. Is this the best way to 
set up the sparse matrix? My problem here is, that I have a constant column block-size and a highly variable row block size.

Thank you,
Jan

**Comment by jbschroder** [comment]
Hi Jan,

I believe that the blocksize in your matrix has to be square (like 4x4) for
PyAMG to carry out it's nodal coarsening, and do block relaxation.  If it
doesn't make sense for your problem's matrix to have a 4x4 block BSR
matrix, then you can always try a straight CSR matrix, and let PyAMG try
and figure out the rest.

Let us know how it goes!

Jacob

**Comment by lukeolson** [comment]
Since there's not a clear path forward here, I'm closing this (open to suggestions!).  It would be good to have an example of a non-square BSR application to work with before digging in too far.
