### ISSUE TITLE
indefinite problem, coarse solver

### ISSUE THREAD

**Issue by nschloe** [pyamg/pyamg#223]
I would like to solve an indefinite problem with pyamg, e.g., the Laplace problem with Neumann boundary conditions. – Possible if the right-hand side is in the image of the operator.
For this to work with MG, the coarse solver cannot be a direct solver, but needs to be set to, e.g., Jacobi. (Compare [this PETSc mailing list entry](https://lists.mcs.anl.gov/pipermail/petsc-users/2012-February/012139.html).) Is this possible in PyAMG yet?

**Comment by lukeolson** [comment]
In addition, if you need to roll your own (e.g. with different smoothing sweeps or weights) you can pass a callable `solver`:
https://github.com/pyamg/pyamg/blob/master/pyamg/multilevel.py#L692

**Comment by nschloe** [comment]
That works, thank you!
