### ISSUE TITLE
Solving AX = B

### ISSUE THREAD

**Issue by jhmarcus** [pyamg/pyamg#225]
Hello pyamg team,

Thank you for a wonderful package! I have found it to be incredibly useful. I was wondering if there was any support for solving a linear system with multiple right hand sides i.e. AX = B where X and B are matrices. 

Thank you,

Joe

**Comment by jbschroder** [comment]
Hi Joe,

I don't believe that we have any support for multiple right-hand-sides.
Sorry.

I'm glad that you find the software useful!

Thanks,

Jacob

**Comment by lukeolson** [comment]
Currently this isn't supported, but we have some progress here: https://github.com/pyamg/pyamg/tree/multiple-rhs

I'll close this for now -- see #215 for updates...

**Comment by jhmarcus** [comment]
Thank you @jbschroder and @lukeolson!
