### ISSUE TITLE
Is there a way to get around the "Microsoft Visual C++" dependency?

### ISSUE THREAD

**Issue by ma-sadeghi** [pyamg/pyamg#228]
When I try to install `pyamg` on Windows, it says that I need Microsoft Visual C++. Is there any workaround? I'm asking because we are interested in adding `pyamg` as our direct solver in our [package ](https://github.com/PMEAL/OpenPNM) since it's super fast, but also want users to be able to install our package with minimum effort via `pip`. I know installing Microsoft Visual C++ is quite simple, but it would be really great if `pyamg` worked without it.

**Comment by jbschroder** [comment]
Hi Amin,

I don't have much experience on Windows, sorry.  Perhaps someone else does.

- Jacob

**Comment by ben-s-southworth** [comment]
PyAMG runs on a C/C++ backend for performance. My understanding of windows is that it doesn't come with a built in C/C++ compiler like Mac and Linux, which may be why you need Microsoft Visual C++. If that is correct, it may be hard to get around that requirement because the C files need to be compiled on your OS.

**Comment by jbschroder** [comment]
I think that Ben is right.  You'll need some kind of C++ compiler on
Windows.

**Comment by ma-sadeghi** [comment]
Thank you for your reply. I wonder how installing `scipy` through `pip` works since that doesn't seem to require a C++ compiler.

**Comment by lukeolson** [comment]
An alternative is that we build some wheels for this. I’ll explore a bit — we have another issue that’s related.

**Comment by ma-sadeghi** [comment]
@lukeolson Really appreciate it

**Comment by lukeolson** [comment]
I’ll try a process similar to scipy to see if that works for you.

**Comment by lukeolson** [comment]
@ma-sadeghi if you're using Python 2.7 try installing with
```
pip install pyamg==3.3.3a1
```

I've uploaded a new wheel for this version (https://pypi.org/project/pyamg/3.3.3a1/#files)

Other wheels can be found in the artifacts of appveyor here: https://ci.appveyor.com/project/LukeOlson/pyamg (click on a failed build then download an artifact).  If any/none of those work, let me know.

I'll complete the auto upload.

**Comment by ma-sadeghi** [comment]
@lukeolson Actually, I'm using Python 3. I tried downloading the `whl` file, but the command line complains that the `whl` file is not a supported wheel on this platform.

Is it possible that this process is done through `pip install pyamg` for Python 3 as well?

Thanks a lot.

**Comment by lukeolson** [comment]
@ma-sadeghi Try `pip install pyamg` now -- I've added wheels for windows and python 3.6:

https://pypi.org/project/pyamg/#files

I may need to add more python versions... just let me know.

**Comment by ma-sadeghi** [comment]
@lukeolson Thanks a million! It worked like a charm.

**Comment by lukeolson** [comment]
Great!   I'll include them with the regular releases.
