### ISSUE TITLE
matlab crash when calling pyamg

### ISSUE THREAD

**Issue by pengfei0803** [pyamg/pyamg#230]
I want to use pyamg in matlab. when I use the code <<ml = py.pyamg.smoothed_aggregation_solver(A, B,struct('max_coarse', 10));>> .matlab will be crashed without any warring. do you know this problem? many thanks

**Comment by jbschroder** [comment]
Hi Peng,

I don't have any experience using Python inside of Matlab, unfortunately.
I'm not sure that the other developers, do either.  But if someone does,
please chime in!

Usually, we use PyAMG natively, inside of a Python environment.

- Jacob

**Comment by lukeolson** [comment]
@pengfei0803 could you provide a small matlab script that reproduces this?

**Comment by pengfei0803** [comment]
no problem. Thank you for your advice
best regards


| |
Li pengfei
|
|
lipengfeihhu@163.com
|
签名由网易邮箱大师定制
On 8/28/2018 20:17，Jacob<notifications@github.com> wrote：
Hi Peng,

I don't have any experience using Python inside of Matlab, unfortunately.
I'm not sure that the other developers, do either. But if someone does,
please chime in!

Usually, we use PyAMG natively, inside of a Python environment.

- Jacob

**Comment by pengfei0803** [comment]
Dear Luke Olson,
thank you for your reply. I attach a matlab script in this email, please find it. it will be crashed in the line 10.
thank you
Best regards
Pengfei 


| |
Li pengfei
|
|
lipengfeihhu@163.com
|
签名由网易邮箱大师定制
On 8/28/2018 22:52，Luke Olson<notifications@github.com> wrote：

@pengfei0803 could you provide a small matlab script that reproduces this?

**Comment by pengfei0803** [comment]
sorry. I forgot to attach it. I sent again. Now you can find the matlab document in the GitHub issue or your email box. Thank you


| |
Li pengfei
邮箱：lipengfeihhu@163.com
|

Signature is customized by Netease Mail Master

On 08/29/2018 00:23, Luke Olson wrote:

@pengfei0803 please just past it here

**Comment by pengfei0803** [comment]
hello，pyamg author,
I have already solved my problem. there is a problem when I installed the python app. I must give the python all the privilege when I use the pyamg library on the matlab.
