### ISSUE TITLE
the form of near-nullspace B

### ISSUE THREAD

**Issue by pengfei0803** [pyamg/pyamg#231]
Dear pyamg authors:
I want to use this library in solid mechanics，but I have a problem about the near-nullspace B. please find the attached one-piece document. I will appreciate it if you can tell me the form of B or  the papers related to the form of B. 
many thanks
pengfei
[near-nullspace B.pdf](https://github.com/pyamg/pyamg/files/2333037/near-nullspace.B.pdf)

**Comment by lukeolson** [comment]
Please take a look here:
https://github.com/pyamg/pyamg/blob/master/pyamg/gallery/elasticity.py

**Comment by ben-s-southworth** [comment]
Think this is a different question - seems like he's asking about the near
null space for a modified system with less DOFs/node but same dimension?
See red at bottom of page
