### ISSUE TITLE
Install on Windows now fails

### ISSUE THREAD

**Issue by jgostick** [pyamg/pyamg#234]
It seems that Numpy has changed something in 1.15, compared to 1.14, so that installations on windows fail.  

Platform: Windows
Python: 3.6
Numpy: 1.15

The error message is: " error: command 'cl.exe' failed: No such file or directory"

So to summarize, on Windows:
numpy 1.14 --> ``pip install pyamg==4`` works just fine
numpy 1.15 --> ``pip install pyamg==4`` fails

Interestingly, with numpy 1.15 ``pip install pyamg==3`` also fails, so the problem seems to be a change in numpy 1.15.

**Comment by lukeolson** [comment]
Were you able to resolve this?

I wonder if the wheels are built for 1.14 but not 1.15 and that VS needs c++ to be installed (are you using VS2015? )

**Comment by jgostick** [comment]
no, have not revisited it.  Sadly we 'temporarily' removed pyamg from our deps, but will add it back asap.

**Comment by lukeolson** [comment]
@jgostick cleaning up some old issues and noticed this was still open.  if there's something to look at on our end, let me know...
