### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by tchaton** [pyamg/pyamg#236]
I am running under Python 3.5.0.

I got this error. 

 File "/home/thomas/.pyenv/versions/3.5.0/envs/Net_Trim/lib/python3.5/site-packages/pyamg/util/utils.py", line 13, in <module>
    import pyamg.amg_core
  File "/home/thomas/.pyenv/versions/3.5.0/envs/Net_Trim/lib/python3.5/site-packages/pyamg/amg_core/__init__.py", line 5, in <module>
    from .evolution_strength import *
ImportError: /home/thomas/.pyenv/versions/3.5.0/envs/Net_Trim/lib/python3.5/site-packages/pyamg/amg_core/evolution_strength.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet

**Comment by lukeolson** [comment]
I think there are some known issues with cython python 3.5.x and compiling against different versions:
https://github.com/pybind/pybind11/issues/314
and
https://github.com/cython/cython/issues/1880

My best suggestion is to update python... but that may not be helpful.

Let me know if this fixes the issue...  Right now we only have osx CI testing for 3.6.  I'll look at adding more to pick up things like this.
