### ISSUE TITLE
PendingDeprecationWarning when using numpy.matrix

### ISSUE THREAD

**Issue by mrkwjc** [pyamg/pyamg#239]
Hi! When using pyamg i get the warning:

> /home/mwojc/Anaconda/lib/python3.7/site-packages/numpy/matrixlib/defmatrix.py:68: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
>     return matrix(data, dtype=dtype, copy=False)

It seems that numpy.matrix is going to be depreciated and removed, so pyamg should not use it at all...

**Comment by lukeolson** [comment]
> so pyamg should not use it at all...

agreed.  I've started replacing some, but finish the rest.

**Comment by lukeolson** [comment]
one update -- summing a BSR matrix, for example, casts the block as a `matrix`:
https://github.com/scipy/scipy/blob/master/scipy/sparse/base.py#L1004

So until scipy fixes this we may not be able to avoid these type of warnings.  We can remove them completely from pyamg however
