### ISSUE TITLE
Segmentation Fault while solving a non-Hermitian Matrix

### ISSUE THREAD

**Issue by apoorvkhattar** [pyamg/pyamg#246]
Hello, I am trying to solve a problem with a large sparse matrix of size (64000,64000), upon running the following code: solve(matA, b_u, verb=True, tol=1.0e-10), the solver says detected a non-hermitian matrix and a segmentation fault is thrown. 
On running the same code on another system this error does not arise and it works as it should. I would like to know is this something related to the newer version of the library or some mistake that I am making that I ought to look for. 
Thanks in advance

**Comment by lukeolson** [comment]
A couple of things come to mind.  In newer versions we've switched to pybind11 which has fixed some memory leaks; this could be related.  Alternatively, do the two systems have the same amount of memory?  4B points is getting large for pyamg.

Also, `.solve()` is very much untested.  Can you tell how far it gets?

**Comment by ben-s-southworth** [comment]
Is your matrix hermitian and are you using Krylov acceleration?

**Comment by apoorvkhattar** [comment]
Thank you fro the reply, the system on which the error is being thrown has 128GB memory(other has 32GB) so I don't think that is the case.
As for .solve() by how far it gets do you know number of iterations? It does not start right after detecting non-hermitian it throws the error. 
For Krylov acceleration, no I am not using that

**Comment by apoorvkhattar** [comment]
I apologize if this sounds stupid but the error was resolved when I used conda to install instead of pip(earlier I had used pip), could there be a reason for this?

**Comment by sreenithy** [comment]
Encountered the same issue on a system with a sufficiently large memory, downgrading pyamg from 4 to 3.2.0 fixed the segmentation fault error.

**Comment by lukeolson** [comment]
Can you provide a small example that throws the error? (And the error?).  Also the matrix size that you’re using.

**Comment by sreenithy** [comment]
The error message just says "Segmentation fault (core dumped)"
This is the function call,
x = pyamg.solve(A,b,verb=False,tol=1e-10)
 Here, A is of shape (147456, 147456), b is of shape (147456,1)
