### ISSUE TITLE
pyamg.krylov.bicgstab gives me an incorrect solution, but converges

### ISSUE THREAD

**Issue by iamhaho** [pyamg/pyamg#248]
** this is unrelated to any of your AMG capabilities.

pyamg.krylov._bicgstab (_bicgstab) gives me an incorrect solution, but scipy.sparse.linalg.bicgstab (bicgstab) gives me the correct one. In order to use _bicgstab I've generated a preconditioner operator M; however, it's for right-preconditioning unlike the description of _bicgstab which requires left. But why does it converge and gives the sense that it worked properly?

**Comment by zhaog6** [comment]
Dear iamhaho,

Do you use unpreconditioned residual or preconditioned residual as convergence criterion? you can look at the convergence history of unpreconditioned residual.


Thanks,
Gang

**Comment by lukeolson** [comment]
closing this. if you have a specific example to look at let us know.  we've made residual vs preconditioned residual clear in the docs now.  see PR #279
