### ISSUE TITLE
Wheel for python 3.8?

### ISSUE THREAD

**Issue by renefritze** [pyamg/pyamg#258]
It would be great to also have a manylinux wheel for python 3.8 for the released version.

**Comment by renefritze** [comment]
Same goes for python 3.9

**Comment by renefritze** [comment]
It looks like version 4.1 only has a macosx wheel, and no manylinux ones. Is that intentional?

**Comment by kyoungseoun-chung** [comment]
> It looks like version 4.1 only has a macosx wheel, and no manylinux ones. Is that intentional?

Same here. In Linux, attempting pyamg installation via pip spit out error message like "The wheel package is not available"...

**Comment by lukeolson** [comment]
I've added automatic wheel builds so this should be addressed now.  up to 3.9 and I'll add 3.10 for the next minor bump.

https://pypi.org/project/pyamg/#files
