### ISSUE TITLE
is pyamg supports non-symmetric matrix ?

### ISSUE THREAD

**Issue by dproxy8** [pyamg/pyamg#263]
Hi, thank you for your great work. I was wondering if your pyamg can handle non-symmetric matrix.
If yes, could you provide me an information how to do that? 

Thank you in advance.
[edit]
I'm in a situation where I have a large sparse non-symmetric matrix and I want to solve it using your pyamg

**Comment by jbschroder** [comment]
Hi,

You could look at these two examples which demonstrate some nonsymmetric
capabilities,
https://github.com/pyamg/pyamg-examples/blob/master/Nonsymmetric/demo_recirc_flow.py

https://github.com/pyamg/pyamg-examples/blob/master/Blackbox/demo.py

Best,

Jacob
