### ISSUE TITLE
Use float instead of numpy.float with numpy 1.20

### ISSUE THREAD

**Issue by lorentzenchr** [pyamg/pyamg#265]
WIth numpy version 1.20, the use of `np.float` and `np.int` etc. is deprecated, see https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations. To silence the DeprecationWarning, one can simply replace `np.float` with `float` (or be more specific like `np.float64`) and so on.

**Comment by lukeolson** [comment]
thanks @lorentzenchr (https://github.com/pyamg/pyamg/commit/dec099b5548674880fa2d59c775bb0095fb476a0)
