### ISSUE TITLE
pyamg for nonsymmetric "Laplace without boundary conditions"?

### ISSUE THREAD

**Issue by nschloe** [pyamg/pyamg#267]
A support question, not a bug report.

I'm looking at a preconditioner for the Laplace system _without_ boundary conditions, i.e. (for finite elements),

![screenshot](https://user-images.githubusercontent.com/181628/112958532-dc9bd000-9142-11eb-8455-cb59375976e2.png)

The resulting matrix has a null space that consists of all linear functions, so its dimensionality is 2 for 1D domains, 3 for 2D domains (see example below), and generally n+1 for nD domains.

The matrix is not self-adjoint (except for 1D), so has complex-valued eigenvalues.

An example with FEniCS (converted to SciPy/NumPy):
```python
import matplotlib.pyplot as plt
import numpy as np
from dolfin import (
    EigenMatrix,
    FacetNormal,
    FunctionSpace,
    TestFunction,
    TrialFunction,
    UnitIntervalMesh,
    UnitSquareMesh,
    assemble,
    dot,
    ds,
    dx,
    grad,
)


def _assemble_eigen(form):
    L = EigenMatrix()
    assemble(form, tensor=L)
    return L


k = 20
# mesh = UnitIntervalMesh(n)
mesh = UnitSquareMesh(k, k)

degree = 1
V = FunctionSpace(mesh, "CG", degree)

u = TrialFunction(V)
v = TestFunction(V)
mesh = V.mesh()
n = FacetNormal(mesh)

A = _assemble_eigen(dot(grad(u), grad(v)) * dx - dot(n, grad(u)) * v * ds).sparray()

out = np.linalg.eigvals(A.toarray())
plt.plot(out.real, out.imag, "o")
plt.show()
```
![f](https://user-images.githubusercontent.com/181628/112958875-2b496a00-9143-11eb-9142-922046348adc.png)

Now, initially I thought that MG wasn't such a good choice here since the matrix isn't self-adjoint. Is this justified? Perhaps I can make use of the fact that I know the right nullspace well. Would that be of any help?

**Comment by jbschroder** [comment]
Hi Nico,

From what you describe, I think MG could work.  When the constant vector is
in the nullspace (say all Neumann BCs, and A 1 = 0), then the constant has
to be projected out of the current solution guess after each MG iteration.
I'm wondering if you can't project out the constant and a linear basis from
the current solution guess after each MG iteration, and get good MG
performance.  I haven't ever done that, but it seems possible.  If
performance isn't good, you could go one step further and pass in the
constant and linears to smoothed aggregation (B = [1, X, Y]), to build a
better interpolation.  Just some ideas!  I hope they're useful.

Cheers,

Jacob

**Comment by nschloe** [comment]
I've actually had good success with that, so thanks for the all the hints. For everyone interested, let me leave behind some reproducing source code:
```python
import numpy as np
import scipy.linalg
import meshzoo
import skfem as fem
from skfem.models.poisson import laplace
import pyamg
from skfem.helpers import dot
import npx
import matplotlib.pyplot as plt


points, cells = meshzoo.rectangle_tri((0.0, 0.0), (1.0, 1.0), 35)
# points, cells = meshzoo.disk(6, 25)


print("skfem")


@fem.BilinearForm
def flux(u, v, w):
    return dot(w.n, u.grad) * v


mesh = fem.MeshTri(points.T, cells.T)
basis = fem.InteriorBasis(mesh, fem.ElementTriP1())
facet_basis = fem.FacetBasis(basis.mesh, basis.elem)

lap = fem.asm(laplace, basis)
boundary_terms = fem.asm(flux, facet_basis)

A = lap - boundary_terms

# np.random.seed(0)
b = np.random.rand(A.shape[1])
# make the system consistent
lns = scipy.linalg.null_space(A.T.toarray()).T
for n in lns:
    b -= np.dot(b, n) / np.dot(n, n) * n


ml = pyamg.smoothed_aggregation_solver(
    A, coarse_solver="jacobi", symmetry="nonsymmetric", max_coarse=100,
    # B=scipy.linalg.null_space(A.toarray())
)
M = ml.aspreconditioner(cycle="V")

x, info = npx.gmres(A, b, tol=1e-12, M=M, maxiter=20)
# res = b - A @ info.xk

plt.semilogy(np.arange(len(info.resnorms)), info.resnorms)
plt.show()
```
![out](https://user-images.githubusercontent.com/181628/113030480-eeef2b80-918d-11eb-8d24-0abe52f73d80.png)
