### ISSUE TITLE
scipy.linalg.pinv2 (in multilevel.py) is deprecated since SciPy 1.7.0

### ISSUE THREAD

**Issue by learning-chip** [pyamg/pyamg#278]
[`scipy.linalg.pinv2`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pinv2.html) is deprecated, in favor of `scipy.linalg.pinv`:
> scipy.linalg.pinv2 is deprecated since SciPy 1.7.0, use scipy.linalg.pinv instead for better tolerance control.

Related code:
https://github.com/pyamg/pyamg/blob/1d2272b88f1a8b5d2e4e39bb01494bcd67f22459/pyamg/multilevel.py#L619-L623

https://github.com/pyamg/pyamg/blob/1d2272b88f1a8b5d2e4e39bb01494bcd67f22459/pyamg/multilevel.py#L99-L104

`pinv2` and `pinv` both use SVD now, and there should be no difference.

**Comment by lukeolson** [comment]
Thanks.  I've pushed some fixes here: 1ed7b6adf276baa9ff84aa3a67dd8da5751e19b2

Of note:
- `pinv` will now be used for scipy >= 1.7
- `pinv` will point to `pinv2` for scipy < 1.7
- `pinv` is updated throughout (mainly in tests, where speed is not an issue)
- `pinv` and `pinv2` still work as strings

I'm not sure we had a use case where someone needed the LS version of the inverse -- in any case, it case still be customized to do this.  If you see that this will cause problems, let me know.
