### ISSUE TITLE
Documentation error in jacobi

### ISSUE THREAD

**Issue by ghbrown** [pyamg/pyamg#281]
The docstring/example for `jacobi` says that it may be imported as
```python
 Examples
    --------
    >>> # Use Jacobi as a Stand-Alone Solver
    >>> from pyamg.relaxation.relaxation.relaxation import jacobi
 ```
(relaxation.py line 377-380)
when it should be
```python
    >>> from pyamg.relaxation.relaxation import jacobi
 ```

The rest of the functions in this module have the correct number of `relaxation`s, and I originally discovered this because the suggested example didn't work.

I can make a PR, but figured it would be easiest if a core developer just made the one line change.

**Comment by lukeolson** [comment]
good catch. fixed here 6eedd6c
