### ISSUE TITLE
add flake8/pylint/pydocstyle to ci

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#285]
linting needs to be added to ci

**Comment by nschloe** [comment]
In case it's interesting to you, you should check out [pre-commit](https://github.com/pre-commit/pre-commit). I found it a few months ago an use it almost everywhere. You basically add a small lint-info file to your repo, e.g., [this one in meshio](https://github.com/nschloe/meshio/blob/main/.pre-commit-config.yaml), run
```
pre-commit install
```
once, and then it'll run the checks _locally_ before every commit. If linting fails, you cannot commit. This has saved my CI queues lost of work. There's also a github action that runs the lints defined in the config (see, e.g., [here](https://github.com/nschloe/meshio/blob/main/.github/workflows/ci.yml#L20)).
