### ISSUE TITLE
reuse old aggregation?

### ISSUE THREAD

**Issue by nschloe** [pyamg/pyamg#295]
For numerical parameter continuation with [pacopy](https://github.com/nschloe/pacopy), I need to solve many equation systems with "similar" matrices many times in succession. The matrices are similar in that they all have _exactly_ the same sparsity pattern, and the values only change slightly from step to step.

Right now, in every step I recompute the preconditioner
```python
ml, _ = pyamg.aggregation.adaptive_sa_solver(P)

def _apply(phi):
    return ml.solve(phi, tol=0.0, maxiter=1)

prec = LinearOperator(
    (len(psi), len(psi)),
    dtype=complex,
    matvec=_apply,
    rmatvec=_apply,
)
```
Is it possible to reuse some of the aggregation information from step to step? The only reference I've found so far is https://github.com/pyamg/pyamg/issues/219.

**Comment by nschloe** [comment]
PS: This isn't an actual "issue" of course, but the pyamg GitHub repo doesn't have _Discussions_ enabled yet. Perhaps that's something to consider. (It's as simple as ticking a box in the _Settings_.)

**Comment by lukeolson** [comment]
I guess we never addressed this (sorry for the silence Nico!).

The main question is what type of information would be helpful to reuse.  If `P` is reconstructed, then you really need to reevaluate `P.T @ A @ P`, and then everything else changes on coarse levels (like #219), unless non-Galerkin is used.  Everything other than `P` is relatively cheap in the setup phase, so I'm not convinced that there are any easy tricks in this situation.  One could look at low-rank updates, augmenting the cycle, etc.  But in the end, adaptive *is* costly -- I think it's an open research question on how to make it more efficient.

@jbschroder any other ideas?

**Comment by nschloe** [comment]
Interesting! (I hadn't seen #219.) Let's close this.
