### ISSUE TITLE
drop vtk-based vis

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#297]
We should consider dropping the vtk-based visualization.  I think it's largely unused and we could replace the functionality with better tools.
- The aggregation vis could be https://github.com/pyamg/pyamg/blob/lloyd-unify/pyamg/vis/aggviz.py
- In short order I could add some (multilevel) splitting visualizations based on some existing scripts
- Drop mesh io altogether (available in other tools)
- What other vis routines would we want?

@jbschroder thoughts?

**Comment by jbschroder** [comment]
Hey Luke,

Yeah, the VTK stuff is mostly leftover from the dissertation days (I
think).  I don't use it anymore, so I'm OK if it's dropped.  The only
advantage to VTK is that paraview (while cluunnkkky) let's you tweak your
visualization in so many ways, that I found it useful.  But from a standard
user's perspective, having pure Python scripts to do the visualizations
would be a lot better.   Anyway, this is just a long way of me saying that
I'm OK with getting rid of the VTK stuff :-)

Cheers,

Jacob

**Comment by lukeolson** [comment]
Ok, that's a fair point.  I *think* we can keep both and just yank out the vtk helper tools in favor of stuff that's more polished (like `meshio`).  I'll sketch something up...

**Comment by jbschroder** [comment]
Cool!  I just looked at meshio by Nico.  That does look like an upgrade
from the old VTK helper tools.

- Jacob

**Comment by lukeolson** [comment]
for now, it was a light fix https://github.com/pyamg/pyamg/issues/306.  If this proves fragile, then let's go with `meshio`.
