### ISSUE TITLE
Unable to import from pyamg.classical in pyamg-4.2.1

### ISSUE THREAD

**Issue by pohm01** [pyamg/pyamg#300]
Using pyamg-4.2.1 installed via pip (the default option) I am unable to import functions from pyamg.classical
For example:
`from pyamg.classical import direct_interpolation`
gives the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'direct_interpolation' from 'pyamg.classical' (/home/pohm/pip-test/lib/python3.8/site-packages/pyamg/classical/__init__.py)`

If I force pip to install pyamg-4.1.0 I am again able to import functions from pyamg.classical.

python version is 3.8.6

**Comment by lukeolson** [comment]
So with `4.2.x` we went to explicit imports, to help avoid some issues with circular imports.  As such, `direct_interpolation` is no longer at the `classical` level.  Instead
```
from pyamg.classical.interpolate import direct_interpolation
```
should work.

Of course ... open to ideas here... if it makes sense to import all of the interpolation operations to `classical` as before, it's super easy to do.

sorry for not making the transition a bit more graceful!

**Comment by pohm01** [comment]
That works! Good to know!
The readthedocs page looks as though it is still for 4.1 in case you weren't aware...

**Comment by lukeolson** [comment]
oh... very good point.

#301
