### ISSUE TITLE
pyamg.vis vtk writers

### ISSUE THREAD

**Issue by jbschroder** [pyamg/pyamg#306]
replace the pyamg.vis vtk writers with a more robust library vtk writer.  Our writers no longer produce compliant vtk files for paraview (e.g., VisualizingAggregation example).

**Comment by jbschroder** [comment]
One more thing, we should test the VTK writers with the pyamg-examples/VisualizingAggregation demos

**Comment by lukeolson** [comment]
> replace the pyamg.vis vtk writers with a more robust library vtk writer. Our writers no longer produce compliant vtk files for paraview (e.g., VisualizingAggregation example).

Turned out to be an easy fix (floats were being written where ints were expected).  #316 


> One more thing, we should test the VTK writers with the pyamg-examples/VisualizingAggregation demos

Updated the demos in 8a69ad5998292154e0093a5974aa83fff312fc11 with #316
