### ISSUE TITLE
scipy imports fail on scipy 1.8.0

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#307]
Scipy is [updating the namespaces in v1.8.0](https://scipy.github.io/devdocs/release.1.8.0.html#clear-split-between-public-and-private-api)

```
  File "/Users/lukeo/repos/pyamg/pyamg/krylov/_gmres_mgs.py", line 8, in <module>
    from scipy.sparse.linalg.isolve.utils import make_system
ModuleNotFoundError: No module named 'scipy.sparse.linalg.isolve.utils'; 'scipy.sparse.linalg.isolve' is not a package
```

It's unclear how to hand this, but one option is 
https://github.com/pyamg/pyamg/blob/main/pyamg/util/utils.py#L11

So 

```python
try:
    from scipy.sparse.linalg._isolve.utils import make_system
except ImportError:
    from scipy.sparse.linalg.isolve.utils import make_system
```

**Comment by xylar** [comment]
conda-forge just updated to scipy 1.8.0 a few hours ago and this is causing errors for me as well in my CI.

**Comment by lukeolson** [comment]
thanks @xylar 

fix coming in #308

**Comment by xylar** [comment]
Thank you, that's wonderful!

**Comment by xylar** [comment]
Thanks again!  Will there be a release soon that includes this patch fix, or should I patch the current release on conda-forge?  I'm fine either way.

**Comment by lukeolson** [comment]
yep I'm working on the release now.. shouldn't take long

**Comment by lukeolson** [comment]
@xylar should be good to go!

*thank you* for your help on the recipe!

**Comment by felipeaugustogudes** [comment]
Hi everyoe! How to fix the problem with scipy 1.8.0, I used:

try:
    from scipy.sparse.linalg._isolve.utils import make_system
except ImportError:
    from scipy.sparse.linalg.isolve.utils import make_system
   
   bur the error continue to show.

**Comment by lukeolson** [comment]
@felipeaugustogudes thanks for this.  What version of PyAMG are you running? `pyamg.__version__`?

**Comment by lukeolson** [comment]
So this import was moved to `utils` -- which suggests that you may have an older version of pyamg installed.  Are you able to paste `pyamg.__version__`?

**Comment by felipeaugustogudes** [comment]
In[5]: pyamg.__version__
Out[5]: '4.1.0'

**Comment by felipeaugustogudes** [comment]
Thanks for all! Now it is working well!
