### ISSUE TITLE
Consider removing `pytest` from install requirements

### ISSUE THREAD

**Issue by xylar** [pyamg/pyamg#309]
In the conda-forge recipe, we have patched to remove `pytest` as an install requirement because this seems to be a testing requirement instead.  

https://github.com/conda-forge/pyamg-feedstock/blob/master/recipe/0001-remove-unneeded-requirement.patch

I would ask you to consider dropping it from `install_requirements` in the next release:
https://github.com/pyamg/pyamg/blob/main/setup.cfg#L46

**Comment by lukeolson** [comment]
This is a great idea (and long overdue).  Added here https://github.com/pyamg/pyamg/pull/310 and it will go out in the next bump.

**Comment by xylar** [comment]
Perfect, thanks again!
