### ISSUE TITLE
pyamg has no attribute 'write_mesh'

### ISSUE THREAD

**Issue by JosephGreenStello** [pyamg/pyamg#314]
Hello,

I am doing a mesh adaptation project at University of Arizona. I am trying to run the simple example codes from the pyamg website on my Linux and it seems 'pyamg.write_mesh' and 'pyamg.adapt_mesh' are no longer working. Were these updated to something new? I looked everywhere else I could so I would appreciate the help. The specific error is : 
```line 52, in <module>
 adapted_mesh = pyamg.adapt_mesh(mesh,remesh_options)
AttributeError: module 'pyamg' has no attribute 'adapt_mesh'```

**Comment by JosephGreenStello** [comment]
> Hello,
> 
> I am doing a mesh adaptation project at University of Arizona. I am trying to run the simple example codes from the pyamg website on my Linux and it seems 'pyamg.write_mesh' and 'pyamg.adapt_mesh' are no longer working. Were these updated to something new? I looked everywhere else I could so I would appreciate the help. The specific error is :
> 
> ```
>  adapted_mesh = pyamg.adapt_mesh(mesh,remesh_options)
> AttributeError: module 'pyamg' has no attribute 'adapt_mesh'```
> 
> 
>  
> ```

Also, I am trying to use pyamg with SU2.

**Comment by lukeolson** [comment]
Hi @JosephGreenStello 

I think you may be looking for the mesh software that (confusingly) goes by the same name: https://pyamg.saclay.inria.fr/pyamg.html

**Comment by JosephGreenStello** [comment]
You're right. Sorry about that.
