### ISSUE TITLE
BSR symmetric strength norm calculation

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#347]
The norm calculation might need a square root:
https://github.com/pyamg/pyamg/blob/main/pyamg/strength.py#L309

**Comment by jbschroder** [comment]
@lukeolson I went back and looked at this some more.  And, I do think the BSR case needs a sqrt.  Right now, a 1x1 BSR matrix has it's data array squared, while a CSR matrix doesn't in 
https://github.com/pyamg/pyamg/blob/main/pyamg/strength.py#L309 
That can't be right.  

If you agree, I can put in a 
data <-- np.sqrt(data) for the BSR
It might break a couple unit tests, but that should be easy to fix.

**Comment by jbschroder** [comment]
PR 349 should fix this (thanks Andrea!)
https://github.com/pyamg/pyamg/pull/349
