### ISSUE TITLE
For geophysical fluid dynamic problems

### ISSUE THREAD

**Issue by miniufo** [pyamg/pyamg#387]
I just came to this interesting package.  I got a lot of elliptic problems in geophysical fluid dynamics (GFD), and a solver called [xinvert](https://github.com/miniufo/xinvert) for finding the solutions.

As the resolution goes higher and higher, I may need to incorporate multigrid method to accelerate the solver.  Just want to know if this package can directly accept a `xarray.DataArray` in which data and coordinates are all defined, and hence a solution is implied.  This could be very helpful for the problems in GFD.

In a global domain, with lat/lon coordinates, there are land/sea grid points.  So invert Poisson equation on ocean grids using multigrid can be problematic because of interpolating the fields between coarse and find grids.  Is there any simple way to deal with this problem?

**Comment by lukeolson** [comment]
@miniufo You would need to create the matrix problem ($$Ax=b$$) -- for this it may be useful to use xarray's `to_numpy`: https://docs.xarray.dev/en/stable/generated/xarray.DataArray.to_numpy.html

Thanks for the question; closing for now...
