### ISSUE TITLE
Krylov FGMRES bug on Apple silicon chips

### ISSUE THREAD

**Issue by eattardo** [pyamg/pyamg#397]
It is probably linked with  #https://github.com/pyamg/pyamg/issues/365, but it seems that the Krylov solver FGMRES behaves differently on Apple silicon chips w.r.t. Windows or Linux machines (with Intel or AMD chips).

While trying to solve a linear system of matrix equations with complex numbers, using FGMRES and Smoothed Aggregation as Preconditioner, the linear system converges nicely under Windows/Linux reporting (with the use of a callback function) the reduced residuum at each iteration. If I run the same script on a Mac with an Apple chip, the residuum is always 1.0.

Something wrong on the Mac side.

I'm using the latest version of PyAMG installed via pip (as suggested on the main page).

**Comment by lukeolson** [comment]
Thanks for reporting this @eattardo.  Do you have the specific call (and callback) to FGMRES?  I'll see if I can reproduce the issue with a complex matrix.

**Comment by eattardo** [comment]
Thanks @lukeolson. 
In principle the calling function uses pyamg.krylov.fgmres with regular SA as a preconditioner would produce this error on complex numbers. The callback is a very simple function (given A the matrix, b the RHS)

def callback_fun_iter(x):
    """ Callback function to be used within pyamg fgmres"
    """
    r = A.dot(x) - b
    nrmR = numpy.linalg.norm(r) / b
    print("iteration ", callback_fun_iter.itDone, "of ", maxIter, ": ", nrmR)
    callback_fun_iter.itDone += 1

**Comment by lukeolson** [comment]
Ok, I'm having trouble reproducing an issue with this:
```python
import numpy as np
import pyamg

maxIter = 100
def callback_fun_iter(x):
    import numpy
    """ Callback function to be used within pyamg fgmres """
    r = A.dot(x) - b
    nrmR = numpy.linalg.norm(r) / numpy.linalg.norm(b)
    print("iteration ", callback_fun_iter.itDone, "of ", maxIter, ": ", nrmR)
    callback_fun_iter.itDone += 1
callback_fun_iter.itDone = 0

np.random.seed(625)
A = pyamg.gallery.gauge_laplacian(100, beta=0.001)
x = np.random.rand(A.shape[0]) + 1.0j * np.random.rand(A.shape[0])
b = np.random.rand(A.shape[0]) + 1.0j * np.random.rand(A.shape[0])

ml = pyamg.smoothed_aggregation_solver(A)

resvec = []
x0 = x.copy()
x = pyamg.krylov.fgmres(A, b, x0=x0, tol=1e-18, restrt=None, maxiter=maxIter,
                        M=ml.aspreconditioner(),
                        callback=callback_fun_iter,
                        residuals=resvec)

```


Do you have something simple we could try in order to track this down?

**Comment by eattardo** [comment]
Unfortunately, I cannot share the linear system that shows the problem. I can share another with you, but this works as expected on Windows and macOS. 

I will debug by myself; it is possible that something is not correct in the original matrix, and that triggers that strange behavior. 

Thanks for the help.

**Comment by lukeolson** [comment]
Sounds good.  If we can reproduce, then let's reopen the issue.
