### ISSUE TITLE
Doesn't run on Python 3.12+

### ISSUE THREAD

**Issue by nschloe** [pyamg/pyamg#400]
I can't run pyamg on Python 3.12 (released Oct '23) with

```
.tox/py3/lib/python3.12/site-packages/pyamg/multilevel.py:10: in <module>
    from pkg_resources import parse_version  # included with setuptools
E   ModuleNotFoundError: No module named 'pkg_resources'
```

This is [fixed in main](https://github.com/pyamg/pyamg/pull/394), but there's no release yet. Perhaps it's time?

**Comment by lukeolson** [comment]
Thanks @nschloe!  I'll work on a release

**Comment by RNarayan73** [comment]
Eagerly awaiting this fix for Python 3.12. Is there an ETA for this, folks?

**Comment by lukeolson** [comment]
We were attempting to fix a non critical warning but can roll this out now. 3.12 works fine -- temporarily you can pip install directly from GitHub.

**Comment by lukeolson** [comment]
just rolled out a release + wheels.  Let me know if any issues arise.
