### ISSUE TITLE
question about the coarse node index of `pyamg.ruge_stuben_solver`

### ISSUE THREAD

**Issue by zhf-0** [pyamg/pyamg#405]
Hello developers, thank you very much for creating such a good software that we can use to solve linear equations in `Python`.

When I ran the demo program [coarse_fine_splitting](https://github.com/pyamg/pyamg-examples/blob/main/coarse_fine_splitting/demo.py), I found out that the index of coarse node is not the same as I expected.  Here is the modified code based on the `demo.py`
```
import pyamg
import numpy as np
import scipy.io as sio
import scipy.sparse as sparse

data = sio.loadmat('square.mat')
A = data['A'].tocsr()

ml = pyamg.ruge_stuben_solver(A, max_levels=2, max_coarse=1, CF='RS',keep=True)
print(ml)

# The CF splitting, 1 == C-node and 0 == F-node
splitting = ml.levels[0].splitting
C_nodes = splitting == 1
F_nodes = splitting == 0

p = ml.levels[0].P
print('P matrix')
print(p)

node_idx = np.arange(A.shape[0])
coarse_idx = node_idx[C_nodes]
print('coarse index =',coarse_idx)
``` 
I print the interpolation matrix `P`, and part of the output is
```
P matrix
  (0, 18)	1.0000000000000002
  (1, 17)	1.0
  (2, 16)	1.0
  (3, 7)	0.49841929279124797
  (3, 8)	0.501580707208752
  (4, 18)	1.0000000000000002
  (5, 25)	1.0000000000000002
  (6, 25)	1.0
  (7, 0)	1.0
  (8, 0)	0.3459586087262331
  (8, 39)	0.6540413912737668
  (9, 1)	0.31874824564301024
  (9, 39)	0.6812517543569897
```

As far as I am concerned, the row index of matrix `P` is the fine index of one node, and the column index is the coarse index of another node. If  $P_{ij} = 1$, then the two nodes are the same node. For example, $P_{0,18}=0$， there exists one node where the fine index is 0 and the coarse index is 18. Therefore, I print the fine index of all coarse nodes, which is
```
coarse index = [7  10  15  20  27  30  32  33  34  35  38  40  46  54  55  56  59  60
  61  63  64  79  86  89  91  92  95 101 103 111 119 123 125 131 137 141
 144 145 146 148 149 150 151 157 160 162 165 171 173 181 185]
``` 
and `coarse_idx[18] = 61`. 

The output shows that the node with a coarse index 18, its fine index is 61, not 0, and there doesn't exist 0 in the `coarse_idx` ! How does this happen?

**Comment by lukeolson** [comment]
In this example it looks like fine index `0` is an F-point and fine index `61` is a C-point (with coarse index `18`).  So `P[0,18]` is an interpolation weight from C-point `61` to F-point `0`.  Does that help clarify?

From the `C` (strength) matrix you can also see that they are strongly connected:
```python
print(C.getrow(0).indices)
print(C.getrow(61).indices)
[ 0  4 43 61]
[ 0  4 43 57 61 70]
```

**Comment by zhf-0** [comment]
Thank you very much for your reply!

I just learned the MG algorithm from the textbook "A Multigrid Tutorial", primarily focusing on the GMG algorithm. So my understanding of the AMG algorithm may be incorrect. 

Based on my knowledge, if there is only one entry in one row of the matrix `P` and the value of the entry is 1, then it means the fine node and coarse node are the same one. Taking $P_{0,18} = 1$ as the example, there is only one entry in the 0-th row and the column index is 18, which means the fine node with index 0 is the same node as the coarse node with index 18. However,  the fine index of the coarse node is 61, not  0. This is the part that puzzles me. Is my understanding of the interpolation matrix `P` in AMG wrong?
