### ISSUE TITLE
NumPy 2.0 issues

### ISSUE THREAD

**Issue by kinnala** [pyamg/pyamg#406]
I was testing some old code against `numpy==2.0rc1` and ran into the following issue:
```
E           AttributeError: `np.deprecate` was removed in the NumPy 2.0 release. Emit `DeprecationWarning` with `warnings.warn` directly, or use `typing.deprecated`.
```
Seems to be used here: [@np.deprecate](https://github.com/pyamg/pyamg/blob/e1fe54c93be1029c02ddcf84c2338a607b088703/pyamg/strength.py#L502)

There might be other incompabilities that I am unaware of.

**Comment by lukeolson** [comment]
Thanks @kinnala.  This appears to be the only issues so far.  Both `ruff` and testing pass with this fix: https://github.com/pyamg/pyamg/pull/407.  I'll dig a bit to see if other changes are needed.

**Comment by lesteve** [comment]
We are hitting this in scikit-learn CI. There is no rush since we can ignore the warning for now, but it would be great if https://github.com/pyamg/pyamg/pull/407 was merged.

**Comment by jorgensd** [comment]
We are aiming to move to numpy 2.0 in DOLFINx (https://github.com/FEniCS/dolfinx/) and we have pyamg in our demos, so would be great to get #407 merged.

**Comment by jakirkham** [comment]
Am I reading correctly that it was merged and placed in the 5.2.0 release?

**Comment by lukeolson** [comment]
Yep -- that's right.  rn I'm working on getting the wheels up on pypi (and having a slight issue).

**Comment by jakirkham** [comment]
Thanks Luke! 🙏

Do you need another set of eyes?

**Comment by lesteve** [comment]
Looks like the wheels have been uploaded to PyPI  https://pypi.org/project/pyamg/#files, so I guess this can be closed?

Thanks a lot @lukeolson :pray:!

**Comment by lukeolson** [comment]
yep, I think the binary wheels are all looking ok.  there remains an issue with the sdist if anyone has ideas:
https://github.com/pyamg/pyamg/actions/runs/9690697265/job/26741266593

thank you for your patience @*everyone!

**Comment by lesteve** [comment]
Maybe you already know this, but one weird thing is that your version looks like a dev version rather than 5.2.0.

For completeness, here is the error:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         The use of local versions in <Version('5.2.1.post1.dev1+gb11728f')> is 
         not allowed. See                                                       
         https://packaging.python.org/specifications/core-metadata for more     
         information.                                        
```

According to https://github.com/pypi/legacy/issues/731#issuecomment-345461596 you are not supposed to upload a version with the `+gb11728f` part.

**Comment by jakirkham** [comment]
Likely `sdist` build process (or something that precedes it) makes the working directory dirty. As a result `setuptools-scm` notes the version as in development. This might be fixable by...

1. Running the `sdist` build outside of the source directory
2. Configuring the `sdist` build to use directories outside of the source directory
3. Finding what contaminates the source directory and adding it to `.gitignore`
4. Using [some `git` workaround]( https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index ) to ignore the change
5. ?

**Comment by lukeolson** [comment]
@jakirkham @lesteve -- thanks for the pointers.  In the end it was an issue with the fetch depth and failing to specify a tag to checkout (on rerunning the action).  The wheels are up along with an sdist (as `v5.2.1`) -- any issues just let us know.

**Comment by jakirkham** [comment]
Thanks Luke! 🙏

**Comment by jakirkham** [comment]
Had a couple observations on build dependencies we should update

Filed in issue: https://github.com/pyamg/pyamg/issues/415
