### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by NoraLoose** [pyamg/pyamg#422]
Thanks for this awesome package! The link to the documentation in the `About` section is broken.
![Screenshot 2024-09-20 at 1 30 19 PM](https://github.com/user-attachments/assets/eb02eaf7-566d-41b3-a54f-c6dc966dc6e2)

I think all that needs to be done is to make the change http://pyamg.github.io/ --> https://pyamg.readthedocs.io/en/latest/.

**Comment by lukeolson** [comment]
Fixed -- thank for finding this!
