### ISSUE TITLE
more binaries/installation instructions

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#53]
It seems most download the install packages.  The install instructions need to be revisited for all archs and the minimum scipy/numpy(/matplotlib) requirements also need to be revisited.<p>Migrated from http://code.google.com/p/pyamg/issues/detail?id=84</p>

**Comment by lukeolson** [comment]
pip is the norm now.  closing this.

**Comment by jbschroder** [comment]
I see.  I'm not actually familiar with pip, but I'll take your word for it.
 :-)
