### ISSUE TITLE
Schwarz Relaxation Only Implemented for CSR Matrices

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#70]
There is a simple overlapping Schwarz relaxation method, but it's only implemented for CSR matrices as of now.  A BSR version could be coded.  As of now, matrices are just converted to CSR for the purposes of relaxation.<p>Migrated from http://code.google.com/p/pyamg/issues/detail?id=117</p>

**Comment by lukeolson** [comment]
no plans.  closing....

**Comment by jbschroder** [comment]
Sounds fine to me.
